# Simple Makefile for calc project
# To build: type "make"
# To clean: type "make clean"

# Build the calc program
calc: main.c add.c sub.c mult.c div.c parser.c overFlowChecker.c
	gcc -o calc main.c add.c sub.c mult.c div.c parser.c overFlowChecker.c

# Remove the compiled program
clean:
	rm -f calc
